#!/usr/bin/env zsh

export PATH=~/bin:~/.local/bin:"$PATH"
export EDITOR=micro
export VISUAL="code --wait"

export CFLAGS="${CFLAGS} -march=native -O2 -pipe"
export CXXFLAGS="${CXXFLAGS} -march=native -O2 -pipe"
export RUSTFLAGS="-Ctarget-cpu=native"

export PYTHONIOENCODING='UTF-8'
export LANG='de_DE.UTF-8'
export LC_ALL='de_DE.UTF-8'
export LC_TIME='ja_JP.UTF-8'

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

alias ls="exa --icons"
alias l="exa -l --icons"
alias ll="exa -l --icons"
alias la="exa -lA --icons"
alias tree="exa --tree --icons"
alias vim="nvim"
alias vi="nvim"
alias cat="bat -pp"

export BAT_THEME="TwoDark"
export PAGER="less -M"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

if [ -f ~/.cargo/env ]; then
  source ~/.cargo/env
fi

source ~/.zinit/bin/zinit.zsh

zinit wait lucid for \
 atinit"zpcompinit; zpcdreplay" \
  Aloxaf/fzf-tab \
 blockf \
    zdharma/fast-syntax-highlighting \
 atload"_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
 blockf \
    zsh-users/zsh-completions

source <(starship init zsh --print-full-init)
eval "$(direnv hook zsh)"

~/.cargo/bin/lolcow-fortune cowsay -fmoose -L


autoload -U colors && colors
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

unsetopt case_glob

setopt always_to_end
setopt auto_list
setopt auto_menu
setopt auto_param_slash
setopt autocd
setopt bang_hist
setopt combining_chars
setopt complete_in_word
setopt extended_history
setopt extendedglob
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify
setopt inc_append_history
setopt long_list_jobs
setopt no_complete_aliases
setopt notify
setopt path_dirs
setopt rc_quotes
setopt share_history

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zhistory