#!/usr/bin/env zsh

export PATH=~/bin:~/.local/bin:"$PATH"
export EDITOR=nvim
export VISUAL="code --wait"

export CFLAGS="${CFLAGS} -march=native -O2 -pipe"
export CXXFLAGS="${CXXFLAGS} -march=native -O2 -pipe"
export RUSTFLAGS="-Ctarget-cpu=native"

export PYTHONIOENCODING='UTF-8'
export LANG='de_DE.UTF-8'
export LC_ALL='de_DE.UTF-8'
export LC_TIME='ja_JP.UTF-8'

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

alias ls="lsd"
alias l="lsd -l"
alias ll="lsd -l"
alias la="lsd -lA"
alias tree="lsd --tree"
alias vim="nvim"
alias vi="nvim"
alias cat="bat --paging=never"

export BAT_THEME="TwoDark"
export PAGER="less -M"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

if [ -f ~/.cargo/env ]; then
  source ~/.cargo/env
fi

source ~/.zinit/bin/zinit.zsh

zinit wait lucid for \
 atinit"zpcompinit; zpcdreplay" \
  Aloxaf/fzf-tab \
 blockf \
    zdharma/fast-syntax-highlighting \
 atload"_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
 blockf \
    zsh-users/zsh-completions \
  bindmap='UPAR -> ^history-substring-search-up; DOWNAR -> history-substring-search-down' \
    zsh-users/zsh-history-substring-search

zinit ice atclone"starship init zsh --print-full-init > starship.zsh" \
      atpull'%atclone' pick"starship.zsh" nocompile'!'
zinit light davidkna/null

~/.cargo/bin/neo-fortune cowsay -f moose -l


autoload -U colors && colors
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

unsetopt case_glob

setopt always_to_end
setopt auto_list
setopt auto_menu
setopt auto_param_slash
setopt autocd
setopt bang_hist
setopt combining_chars
setopt complete_in_word
setopt extended_history
setopt extendedglob
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify
setopt inc_append_history
setopt long_list_jobs
setopt no_complete_aliases
setopt notify
setopt path_dirs
setopt rc_quotes
setopt share_history
